### ISSUE TITLE
Add prefix capability

### ISSUE THREAD

**Issue by douglaskazumi** [JerryKhw/figma-exporter#1]
Hi Jerry, great plugin for Figma! Is there any chance you could add a feature were Figma Exporter accepts a prefix (and possibly a suffix) and applies it to the exported images?

Thank you

**Comment by JerryKhw** [comment]
Hello. @douglaskazumi Thank you for the issue!

Does the feature you requested add prefixes and suffixes to all images you want to export?

**Comment by douglaskazumi** [comment]
Yes! Thanks for the prompt response.

Just for illustration purposes, the use case is something like this:

Let's suppose the Figma images are named "car", "ball" and "phone" but for some reason I want to follow some kind of naming pattern, like the commonly used "ic_" for icons. It would be nice to indicate that to the plugin and have the exported files be "ic_car", "ic_ball" and "ic_phone".

And since we're at it, it would be even nicer if spaces and dahes where replaced by underscores, since they're not valid for Android resources. Right now dashes are preserved and spaces are removed.

Thank you

**Comment by JerryKhw** [comment]
Yes, thank you for the detailed explanation.

There is a part of what you said that says, "Replace spaces and dashes with underscores," and this request will create a separate text replacement function.
This plug-in can export other platforms to targets in addition to Android, so we will implement text replacement separately function.

**Comment by douglaskazumi** [comment]
Sorry, what I meant to say is to replace these characters when the Android option is selected, since there are not valid characters for Android.

**Comment by JerryKhw** [comment]
Okay. I'll implement it in the way you mentioned, and I'll add a text replacement function later.

**Comment by douglaskazumi** [comment]
That's perfect! Thanks for the responsiveness!

**Comment by JerryKhw** [comment]
@douglaskazumi 
Added feature completed.
Please check once!

**Comment by douglaskazumi** [comment]
@JerryKhw thanks for the quick response time. I'll sure to donate to your project. Meanwhile, there seems to be a bug:

Whenever the suffix is empty, the file is generated with "undefined" in the name. Thank you

**Comment by JerryKhw** [comment]
@douglaskazumi 
Thank you for your donation!
I just fixed the issue and published it.

**Comment by douglaskazumi** [comment]
Thank you! It's working as expected now!
